#+title: =/home/alc/=
#+subtitle: Anthony Le Cigne's personal website
#+options: num:nil

Welcome to my (rather minimalistic) website.

Since it was "under construction" for years, I decided to simply use
it for [[file:notes/notes.org][public notes]] and let it evolve organically from there, in both
form and content.

There is no comment section, but if you feel like dropping a word, you
can use the [[https://github.com/alecigne/lecigne.net/discussions][Discussions section]] of the corresponding [[https://github.com/alecigne/lecigne.net][GitHub repo]].

* Organization
:PROPERTIES:
:CREATED:  [2024-02-17 Sat 22:40]
:END:

- [[file:news.org][News]]: just a (manual) feed about what I consider to be significant
  updates (on my website's scale 😄).

- [[file:notes/notes.org][Notes]]: just because "articles" was a bit too pompous, but that's
  what they are -- reference documents that can evolve with time.

- [[file:projects/projects.org][Projects]]: projects, or "microsites" as I call them, are independant
  GitHub repositories that use the same documentation format as this
  website ([[https://orgmode.org/][Org mode]]). They're "injected" into this website during the
  publishing process which, of course, is taken care of by the One
  True Editor -- [[https://www.gnu.org/software/emacs/][Emacs]].

- [[file:themes/themes.org][Themes]]: a few pages describing my main centers of interest, with
  backlinks that refer to notes

And a little bit separated from the rest, including visually:

- The [[https://lecigne.net/blog/][feed]] section, just a visual feed.

* About me

Since 2018, I am working as a [[https://fr.linkedin.com/in/anthonylecigne][software engineer]], using mainly Java. In
a past life, I worked in cancer research -- I received a PhD in
cellular biology in 2016.

You can find a few of my software projects on [[https://github.com/alecigne][GitHub]].

A few things I'm interested in and you might read about, /one day/, on
this website, in no particular order, is available in the [[file:themes/themes.org][themes]] page,
with links to content when available.

* About the website

These pages have been written with [[https://www.gnu.org/software/emacs/][Emacs]] [[https://orgmode.org/][Org-mode]]. The publishing
process is fully automatic, using Emacs in batch mode:

1. The [[https://github.com/alecigne/lecigne.net][website itself]], a network of Org files kept under version
   control, is "augmented" with other Org [[file:projects/projects.org][projects]] (or "microsites").

2. All Org files are [[https://orgmode.org/manual/Publishing.html][exported]] to HTML.

3. The export is uploaded to my FTP using [[https://rclone.org/][rclone]].

This publishing process can easily be carried out on my Android phone
when I'm on the go. For this, I use [[https://termux.com/][Termux]] and the great [[https://github.com/orgzly/orgzly-android][Orgzly]] to
edit my notes.

The whys and hows of this setup will be addressed one day in a [[file:notes/notes.org][note]].
