#+TITLE: Anthony Le Cigne's public notes

Welcome to my - rather minimalistic - website.

Since it was "under construction" for years, I decided to simply use
it for [[file:notes/notes.org][public notes]] and let it evolve from there.

* About me

Since 2018, I am working as a software engineer, using mainly Java. In
a past life, I worked in cancer research - I received a PhD in
cellular biology in 2016.

Although my long-term goal is to become a confirmed software
craftsman, I consider myself an apprentice, in the sense described in
the book [[https://isbnsearch.org/isbn/9780596518387][Apprenticeship Patterns]] by Hoover and Oshineye.

* About the website

These public notes are a way for me to put into practice the Share
What You Learn pattern described in the book above.

These pages have been written with [[https://www.gnu.org/software/emacs/][Emacs]] [[https://orgmode.org/][Org-mode]]. The publishing
process is fully automatic, using Emacs in batch mode:

1. The [[https://github.com/alecigne/lecigne.net][website itself]], a network of Org files kept under version
   control, is "augmented" with other Org projects (such as my [[https://github.com/alecigne/.emacs.d/][Emacs
   configuration]]).

2. All Org files are [[https://orgmode.org/manual/Publishing.html][exported]], of course to HTML to generate the
   website, but also to PDF and TXT.

3. The export is uploaded to my FTP using [[https://rclone.org/][rclone]].

This publishing process can easily be carried out on my Android phone
when I'm on the go. For this, I use [[https://termux.com/][Termux]] and the great [[https://github.com/orgzly/orgzly-android][Orgzly]] to
edit my notes.

The whys and hows of this setup will be addressed one day in a [[file:notes/notes.org][note]].
