#+title: News
#+options: num:nil

* [2023-08-15 Tue]
:PROPERTIES:
:CREATED:  [2023-08-15 Tue 17:50]
:END:

Wow, some activity:

- A new [[file:notes/compiling-emacs.org][note]] about how I usually compile Emacs.

- Another [[file:notes/signal-export.org][note]] about exporting [[https://signal.org/][Signal]] backups to various formats.

Also, I disabled exports in PDF and TXT to simplify the exporting
process.

* [2021-08-20 Fri]
:PROPERTIES:
:CREATED:  [2021-08-20 Fri 14:10]
:END:

A new [[file:notes/qemu.org][note]] about using QEMU.

* [2020-09-27 Sun]

A new [[file:notes/i3-xmodmap.org][note]] about running xmodmap when starting the i3 window manager.

* [2020-09-26 Sat]

I have improved the way I publish this website. A secondary effect is
that you now can download my [[file:notes/notes.org][notes]] in different formats such as PDF or
TXT (this is experimental and will be improved).

* [2020-05-08 Fri]

A new [[file:notes/git-fu.html][note]] about Git tricks I'd like to remember :)

* [2020-04-19 Sun]

I updated the [[file:notes/common-lisp.html][note]] about setting up a Common Lisp environment.
