#+title: Setting up a Common Lisp environment
#+author: Anthony Le Cigne
#+options: num:nil

Setting up a Common Lisp environment is not easy for beginners. In
this note[fn:1], we will take a logical and progressive approach:

1. SBCL -> Common Lisp implementation.
2. Emacs + Sly -> Common Lisp IDE.
3. ASDF -> build system.
4. Quicklisp -> package manager.
5. Quickproject -> easy creation of Common Lisp projects as ASDF
   systems.
6. Buildapp -> easy compilation for your Lisp projects.
7. StumpWM -> full-blown Common Lisp window manager that will lispify
   your desktop experience.

You can already stop after step 2 and be productive in Lisp, or study
the many great [[https://github.com/alecigne/lisp-books][Lisp books]] out there.

* SBCL

I use [[http://www.sbcl.org/][SBCL]] as my Common Lisp implementation of choice. Source code and
binaries can be found [[http://www.sbcl.org/platform-table.html][here]].

I usually prefer to install the latest version instead of relying on
my distro's current version (although I use Debian Sid). Relevant
quote from [[https://github.com/stumpwm/stumpwm][StumpWM's GitHub page]] (a Common Lisp window manager that we
will install below):

#+begin_quote
Please do /not/ install SBCL using your distributions package manager,
especially Ubuntu. If you do so it is likely that you'll run into
problems when building StumpWM due to using obsolete versions of the
dependencies.
#+end_quote

As of [2026-03-08 Sun], we will download [[http://prdownloads.sourceforge.net/sbcl/sbcl-2.6.2-x86-64-linux-binary.tar.bz2][SBCL v2.6.2]]. I prefer to
install SBCL in =~/bin= and to create a symlink (=~/bin= is in my
PATH). From the directory in which you downloaded the tarball:

#+begin_src sh
  tar xavf sbcl-2.6.2-x86-64-linux-binary.tar.bz2
  cd sbcl-2.6.2-x86-64-linux
  mkdir ~/bin/sbcl-2.6.2
  INSTALL_ROOT=/home/alc/bin/sbcl-2.6.2 sh install.sh
  ln -s ~/bin/sbcl-2.6.2/bin/sbcl ~/bin/sbcl
#+end_src

Adapt this to your own needs, of course. Test the install:

#+name: sbcl-version
#+begin_src bash :results verbatim :exports both
  sbcl --version
#+end_src

#+RESULTS: sbcl-version
: SBCL 2.6.2

* Sly

With just SBCL and Emacs as an IDE, you can already start hacking in
Common Lisp.

I personally use [[https://github.com/joaotavora/sly][Sly]], but [[https://common-lisp.net/project/slime/][SLIME]] is another option. Here's how I
install it in Emacs with =use-package= -- you will find this code in
my Emacs configuration [[https://github.com/alecigne/.emacs.d/blob/master/lisp/alc/alc-tools.el][here]]:

#+BEGIN_src elisp
  (use-package sly
    ;; Sylvester the Cat's Common Lisp IDE.
    ;; https://github.com/joaotavora/sly
    :ensure t
    :config
    (setq inferior-lisp-program "sbcl"
          org-babel-lisp-eval-fn #'sly-eval))
#+end_src

You can also using the package manager directly:

#+begin_example
  M-x package-install RET sly RET
#+end_example

However, don't forget to set your default Lisp by evaluating this
expression:

#+begin_src emacs-lisp
  (setq inferior-lisp-program "sbcl")
#+end_src

Launch it with ~M-x sly~ and start exploring! Sly will run SBCL for
you and connect to the Lisp image. To quit, you can type =,= and
choose the =sayoonara= command.

* ASDF

[[https://common-lisp.net/project/asdf/asdf/Configuring-ASDF-to-find-your-systems.html][Another System Definition Facility]]. ASDF is bundled with SBCL.

In this section we will simply register our ASDF systems. You can use
any directory you want for this; I'll use =~/src/= below. These
instructions are documented [[https://common-lisp.net/project/asdf/asdf/Configuring-ASDF-to-find-your-systems.html][here]], as of [2026-03-08 Sun].

1. Create the configuration directory for ASDF.

   #+begin_src sh
     mkdir ~/.config/common-lisp/source-registry.conf.d/
   #+end_src

2. Create a =.conf= file -- I use =my-asdf.conf=. In this file, add a
   line like this one:

   #+begin_src lisp
     (:tree "/home/alc/src/")
   #+end_src

   You should find this file [[https://github.com/alecigne/dotfiles/blob/master/common-lisp/.config/common-lisp/source-registry.conf.d/my-asdf.conf][in my dotfiles]].

   This will tell ASDF to recursively scan this directory looking for
   =.asd= files. Of course choose your own dir 🙂

3. We will test things by creating a typical ASDF system in the
   directory you used above:

   #+begin_src sh
     mkdir my-asdf-test
   #+end_src

   Then create these 2 files:

   #+begin_src lisp
     ;; my-asdf-test.asd (system definition)

     (asdf:defsystem #:my-asdf-test
       :serial t
       :components ((:file "my-asdf-test")))

     ;; my-asdf-test.lisp (package + a small function)

     (defpackage #:my-asdf-test
       (:use #:cl))

     (in-package :my-asdf-test)

     (defun main ()
       (write-line "Hello, world"))
   #+end_src

4. Here's a Sly session that shows that ASDF can detect the system:

   #+begin_example
     CL-USER> (asdf:load-system :my-asdf-test)
     ; compiling file "/home/alc/src/my-asdf-test/my-asdf-test.lisp" (written 08 MAR 2026 05:20:57 PM):
     ; wrote /home/alc/.cache/common-lisp/sbcl-2.6.2-linux-x64/home/alc/src/my-asdf-test/my-asdf-test-tmpGHU3ALSV.fasl
     ; compilation finished in 0:00:00.008
     T
     CL-USER> (in-package :my-asdf-test)
     #<PACKAGE "MY-ASDF-TEST">
     MY-ASDF-TEST> (main)
     Hello, world
     "Hello, world"
   #+end_example

* Quicklisp

[[https://www.quicklisp.org/beta/][Quicklisp]] is a library manager for Common Lisp. If you need a
dependency for your project, it's a good place to start.

** Slow version
:PROPERTIES:
:CREATED:  [2026-03-08 Sun 15:41]
:END:

1. Download the install script.

   #+begin_src sh
     wget https://beta.quicklisp.org/quicklisp.lisp
   #+end_src

2. Run SBCL and load the Lisp file.

   #+begin_src sh
     sbcl --load quicklisp.lisp
   #+end_src

3. Install Quicklisp. I prefer to install it in =~/.quicklisp=,
   install it wherever you want.

   #+begin_src lisp
     (quicklisp-quickstart:install :path ".quicklisp/")
   #+end_src

4. Notify SBCL about Quicklisp. Add this to your =.sbclrc= file:

   #+begin_src lisp
     #-quicklisp
     (let ((quicklisp-init (merge-pathnames ".quicklisp/setup.lisp"
                                            (user-homedir-pathname))))
       (when (probe-file quicklisp-init)
         (load quicklisp-init)))
   #+end_src

** Fast version
:PROPERTIES:
:CREATED:  [2026-03-08 Sun 15:42]
:END:

#+begin_src sh
  curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
  sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit
#+end_src

** Optional

Run Sly in Emacs and download a package. Here's a Sly session you can
reproduce:

#+begin_example
  ;
  ;  ( \
  ;   \ \
  ;   / /                |\\
  ;  / /     .-`````-.   / ^`-.
  ;  \ \    /         \_/  {|} `o
  ;   \ \  /   .---.   \\ _  ,--'
  ;    \ \/   /     \,  \( `^^^   Take this REPL, brother, and may it serve you well.
  ;     \   \/\      (\  )
  ;      \   ) \     ) \ \
  ;       ) /__ \__  ) (\ \___
  ;      (___)))__))(__))(__)))
  ;
  ; Dedicated output stream setup (port 45563)
  ; Redirecting all output to this MREPL
  ; SLY NIL (#<MREPL mrepl-1-1>)
  CL-USER> (ql:quickload "alexandria")
  To load "alexandria":
    Load 1 ASDF system:
      asdf
    Install 1 Quicklisp release:
      alexandria
  ; Fetching #<URL "http://beta.quicklisp.org/archive/alexandria/2024-10-12/alexandria-20241012-git.tgz">
  ; 55.94KB
  ==================================================
  57,281 bytes in 0.02 seconds (2796.92KB/sec)
  ; Loading "alexandria"
  [package alexandria]..............................
  [package alexandria-2]
  ("alexandria")
  CL-USER> (alexandria:clamp 150 0 100)
  100 (7 bits, #x64, #o144, #b1100100)
#+end_example

(=clamp= clamps a number value into [min, max] range. See [[https://alexandria.common-lisp.dev/][Alexandria]]'s
documentation.)

Since Quicklisp and ASDF work together, you can also load your own
ASDF systems with ~ql:quickload~ instead of what we did above with
~asdf:load-system~. Note that you can put your ASDF systems in
=~/.quicklisp/local-projects=.

* Quickproject

[[https://www.xach.com/lisp/quickproject/][Quickproject]] is pretty neat for creating a Common Lisp project from
scratch. We will use it to create another small test project, but
faster this time. The project we create here will also be compiled in
the next section.

1. Using Sly, create a project in the source directory you selected
   earlier:

   #+begin_src lisp
     (ql:quickload :quickproject)
     (quickproject:make-project #p"~/src/my-quickproject-test/")
   #+end_src

2. In =my-quickproject-test.lisp=, add this ~main~ function after the
   ~in-package~ declaration:

   #+begin_src lisp
     (defun main (argv)
       (format t "Hello, ~A~%" (second argv)))
   #+end_src

3. Load the project:

   #+begin_src lisp
     (ql:quickload :my-quickproject-test)
   #+end_src

If it loads, perfect -- go to the next section 🙂

* Compilation

[[https://www.xach.com/lisp/buildapp/][Buildapp]] is pretty cool.

1. Install it.

   #+begin_src lisp
     (ql:quickload :buildapp)
   #+end_src

2. Build =buildapp= itself.

   #+begin_src lisp
     (buildapp:build-buildapp)
   #+end_src

   *Important*: the binary will be created in the current directory,
   so move it somewhere useful (I'll use =~/bin= as it's in my PATH).

3. We'll now build =my-quickproject-test=!

   #+begin_src sh
     ~/bin/buildapp --output my-quickproject-test \
                    --load-system my-quickproject-test \
                    --entry my-quickproject-test:main
   #+end_src

4. Run the program with an argument:

   #+begin_example
     ❯ ./my-quickproject-test "World"
     Hello, World
   #+end_example

* StumpWM

[[https://github.com/stumpwm/stumpwm][StumpWM]] is a fantastic window manager written and configurable in
Common Lisp. We will build it from source.

You can also check [[https://wiki.archlinux.org/title/Stumpwm][this page]] on ArchWiki.

1. Clone the StumpWM repository:

   #+begin_src bash
     git clone https://github.com/stumpwm/stumpwm
   #+end_src

2. Install the dependencies in SBCL/Sly:

   #+begin_src lisp
     (ql:quickload '("clx" "cl-ppcre" "alexandria"))
   #+end_src

3. Compile it:

   #+begin_src bash
     ./autogen.sh
     ./configure
     make
   #+end_src

4. I prefer to link to the executable instead of using =make install=:

   #+begin_src bash
     ln -s ~/src/stumpwm/stumpwm ~/bin/stumpwm
   #+end_src

5. I start StumpWM with:

   #+begin_src sh
     WM=stumpwm startx
   #+end_src

  Here's the corresponding =~/.xinitrc= file; adapt it to your own
  needs (I also use [[https://i3wm.org/][i3]]):

   #+begin_src bash
     #!/bin/sh

     WM="${WM:-i3}"

     case "$WM" in
       stumpwm)
         xrandr --dpi 96
         export SBCL_HOME=/home/alc/bin/sbcl-2.6.2/lib/sbcl
         exec "$HOME/bin/stumpwm"
         ;;
       i3)
         xrandr --dpi 96
         exec i3
         ;;
       ,*)
         echo "Unknown WM: $WM"
         exit 1
         ;;
     esac
   #+end_src

   Notice the =SBCL_HOME= export, it's important! The cause is [[https://github.com/stumpwm/stumpwm/issues/760#issuecomment-612226954][here]].

6. Run ~WM=stumpwm startx~: it should work.

** Optional: Slynk

You can connect to the Lisp image used by StumpWM from Sly and
interact with the window manager live using a Slynk server (no need to
restart your window manager, you're in the Lisp world).

Check my config [[https://github.com/alecigne/.stumpwm.d][here]], that's what I do.

1. Add this to your StumpWM =init.lisp=:

   #+begin_src lisp
     (in-package #:stumpwm)

     (ql:quickload '(:alexandria :slynk :local-time) :silent t)

     (defvar *slynk-server* nil)

     (defcommand slynk-start () ()
       (unless *slynk-server*
         (setf *slynk-server* (slynk:create-server :port 4006 :dont-close t)))
       (message "Slynk server started."))

     (defcommand slynk-stop () ()
       (when *slynk-server*
         (slynk:stop-server *slynk-server*)
         (setf *slynk-server* nil)
         (message "Slynk server stopped.")))
   #+end_src

2. From StumpWM, run the =slynk-start= command.

3. Then from Emacs, run =M-x sly-connect= and connect to
   =http://localhost:4006=. You should be able to communicate with
   StumpWM! Try it:

   #+begin_example
     CL-USER> (stumpwm:message "hello")
   #+end_example

   The message should appear on the screen. How cool is that?

** Optional: =ttf-fonts=
:PROPERTIES:
:CREATED:  [2026-03-08 Sun 21:18]
:END:

If you want to use the =ttf-fonts= module from [[https://github.com/stumpwm/stumpwm-contrib][StumpWM's contrib
repository]], you will need =clx-truetype=, which is not in Quicklisp
anymore. Here's how to fix that:

1. Clone a version of it in =~/.quicklisp/local-projects=.

   I used [[https://github.com/l04m33/clx-truetype][this one]].

2. Run ~(ql:quickload "clx-truetype")~ once so dependencies are
   fetched (you can also include this line of code in your config).

3. It should work. I personally use Jetbrains Mono:

   #+begin_src lisp
     (load-module "ttf-fonts")
     (xft:cache-fonts)
     (set-font (make-instance 'xft:font
                              :family "JetBrains Mono"
                              :subfamily "Regular"
                              :size 12
                              :antialias t))
   #+end_src

* Other tools
:PROPERTIES:
:CREATED:  [2026-03-08 Sun 21:28]
:END:

Also check:

- [[https://roswell.github.io/][Roswell]]
- [[https://github.com/fukamachi/qlot][Qlot]]
- [[https://github.com/ocicl/ocicl][ocicl]]
- [[https://www.clpm.dev/][CLPM]]
- etc.

* Footnotes

[fn:1] This article was originally written around 2020 and was updated
in 2026.
